import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react';
import { useEffect } from 'react';


function mudarMapa(url) {
  alert(url)
  localStorage.setItem("mapa", url)
  mostrarMapa()
}

function mostrarMapa() {
  //let urlMapa = localStorage.getItem("mapa")
  //return (<div className="row">
  ///  <iframe id="map" src={urlMapa} width="600" height="450" allowFullScreen="" loading="lazy" referrerPolicy="no-referrer-when-downgrade">
  //  </iframe>
  //</div>)
}

function tabela() {
  const [data, setData] = useState(null)
  const [isLoading, setLoading] = useState(false)
  const [cardContent, setcardContent] = useState(false)



  useEffect(() => {
    setLoading(true)
    fetch('http://localhost:5000/get')
      .then((res) => res.json())
      .then((data) => {
        setData(data)
        setLoading(false)
        console.log(data)
        largura()
      })
  }, [])
  if (isLoading) return <tbody><tr><td>carregando</td></tr></tbody>
  if (!data) return <tbody><tr><td>Nenhum registro encontrado</td></tr></tbody>
  function status(status) {
    var ret = ""
    if (status == "rompido") {
      ret = <td > <a clasName="btn-floating pulse"><i class="material-icons">not_interested</i></a></td>
    } else {
      ret = <td > <i class="material-icons">brightness_1</i></td>
    }
    return ret

  }

  return (
    <div className="row">
      <div className='col s5 m5 l5 offset-s1 offset-m1 offset-l1'>
        <table>
          <thead>
            <tr>
              <th>Status</th>
              <th>Cidade/UF</th>
              <th>Bairro</th>
              <th>Rua</th>
              <th><a className="btn" onClick={(e) => reload()}>Atualizar</a></th>
            </tr>
          </thead>
          <tbody>
            {

              data.dados.map((valor) => (
                <tr key={valor.id}>
                  {
                    status(valor.status)
                  }

                  <td>{valor.cidade}/{valor.estado}</td>
                  <td>{valor.bairro}</td>
                  <td>{valor.rua}</td>
                  <td ><a className=" btn " onClick={(e) => setcardContent(
                    <div>
                      <div>
                        <h4><strong>Detalhes</strong></h4>
                        <p>Fibra {valor.status} com perda de potencia de {valor.perda}db <br></br>
                          a uma distancia distancia de {valor.distancia}km</p>
                      </div>
                      <div className="card">
                        <iframe id="map" src={valor.mapa} width="600" height="300" allowFullScreen="" loading="lazy" referrerPolicy="no-referrer-when-downgrade">
                        </iframe>
                      </div>

                    </div>
                  )} >visualizar</a></td>

                </tr>
              ))
            }
          </tbody>
        </table>
        <div className="row " display="none">
          <div className="col offset-s3">
            <ul className="pagination">
              <li className="disabled"><a href="#!"><i className="material-icons">chevron_left</i></a></li>
              <li className="active"><a href="#!">1</a></li>
              <li className="waves-effect"><a href="#!">2</a></li>
              <li className="waves-effect"><a href="#!">3</a></li>
              <li className="waves-effect"><a href="#!">4</a></li>
              <li className="waves-effect"><a href="#!">5</a></li>
              <li className="waves-effect"><a href="#!"><i className="material-icons">chevron_right</i></a></li>
            </ul>
          </div>
        </div>
      </div>
      <div className='col s6 m6 l6'>
        {cardContent}
      </div>
    </div>
  )
}

export default function Home() {
  const [mapa, setMapa] = useState(null)

  var valores = {
    dados: [{
      cidade: "teste",
      bairro: "Jardim Botânico",
      rua: "Rua Santana",
      estado: "sp",
      distancia: "14.614",
      perda: "0.072",
      latitude: "-25.43904",
      longitude: "-49.245825"
    }]
  }


  return (
    <div className="container">
      <Head>
        <title>Smart Sensors</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"></link>
      </Head>
      <div className="row">
        <nav>
          <div className="nav-wrapper  blue darken-2">
            <a href="#" className="brand-logo center">Smart Sensors</a>
            <ul id="nav-mobile" className="right hide-on-med-and-down">
              <li><a href="">Monitoramento</a></li>
              <li><a href="">Sobre nos</a></li>
              <li><a href="">Contato</a></li>
              <li><a href=""><i className='material-icons'>settings</i></a></li>

            </ul>
          </div>
        </nav>
      </div>
      <div className="row">
        <div className="col s12 m12 l12">

        </div>
      </div>
      <div className="row">
        <div className="col offset-s2">
            <h4><strong>Modulos</strong></h4>
        </div>
        <table>
          {tabela()}
        </table>
      </div>
      {
        mostrarMapa()
      }
      <div className="row">
        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' Smart Sensors'}
          </a>
        </footer>
      </div>
    </div>

  )
}
function largura() {
  var largura = window.innerWidth
  document.querySelector(".container").style.margin = 0;
  document.querySelector(".container").style.width = largura + "px";
}

function reload() {
  document.location.reload(true)
}
